[package]
name = "grpc"
version = "0.2.5-alpha.0"
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
description = "gRPC client implementation for io-driver-based applications"

[dependencies]
bytes = { workspace = true }
http2 = { workspace = true }
io-driver = { workspace = true }

[dev-dependencies]
