[package]
name = "protocol-resp-fuzz"
version = "0.0.0"
publish = false
edition = "2024"

[workspace]

[package.metadata]
cargo-fuzz = true

[dependencies]
libfuzzer-sys = "0.4"

[dependencies.protocol-resp]
path = ".."
features = ["resp3"]

[[bin]]
name = "fuzz_value_parse"
path = "fuzz_targets/fuzz_value_parse.rs"
test = false
doc = false
bench = false

[[bin]]
name = "fuzz_command_parse"
path = "fuzz_targets/fuzz_command_parse.rs"
test = false
doc = false
bench = false
