[package]
name = "protocol-ping"
version = "0.3.2"
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
description = "Simple ASCII PING/PONG protocol implementation"

[dependencies]
thiserror = { workspace = true }
