name: Test Firecracker
on: workflow_dispatch

jobs:
  test:
    runs-on: [self-hosted, firecracker]
    steps:
      - run: |
          echo "Hello from Firecracker!"
          uname -a
          rustc --version

