[package]
name = "metrics"
version = "0.2.17-alpha.0"
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
description = "High-performance sharded metrics with metriken integration"

[dependencies]
metriken = { workspace = true }
